stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: $DOCKER_USERNAME/student-app

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest

push:
  stage: push
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  script:
    - kubectl set image deployment/student-app student-app=$IMAGE_NAME:latest -n student-ns
    - kubectl rollout status deployment/student-app -n student-ns