stages:
  - build
  - push
  - deploy

variables:
  IMAGE_NAME: "$DOCKER_USERNAME/student-app"

build:
  stage: build
  tags:
    - student-app

  script:
    - docker --version
    - docker build -t "$IMAGE_NAME:latest" .

push:
  stage: push
  tags:
    - student-app

  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push "$IMAGE_NAME:latest"

deploy:
  stage: deploy
  tags:
    - student-app

  script:

    # Create Kind cluster if is not exist
    - |
      if kind get clusters | grep -q "^student22$"; then
        echo "Kind cluster already exists."
      else
        kind create cluster --name student22 --config kubernetes/config.yml
      fi

    # Wait for node
    - kubectl wait --for=condition=Ready node --all --timeout=180s

    # Create Namespace
    - |
      if kubectl get namespace student-ns >/dev/null 2>&1; then
        echo "Namespace student-ns already exists."
      else
        kubectl apply -f kubernetes/namespace.yml
      fi

    # Create Pv
    - |
      if kubectl get pv mysql-pv >/dev/null 2>&1; then
        echo "PV mysql-pv already exists."
      else
        kubectl apply -f kubernetes/pv.yml
      fi

    # Create Pvc
    - |
      if kubectl get pvc mysql-pvc -n student-ns >/dev/null 2>&1; then
        echo "PVC mysql-pvc already exists."
      else
        kubectl apply -f kubernetes/pvc.yml
      fi


    - kubectl apply -f kubernetes/mysql-service.yml


    - kubectl apply -f kubernetes/mysql-deployment.yml


    - kubectl apply -f kubernetes/service.yml

    - kubectl apply -f kubernetes/deployment.yml

    - kubectl rollout status deployment/student-app -n student-ns --timeout=180s

    - kubectl get deployment -n student-ns

    - kubectl get pods -n student-ns
